# Generated by Django 3.2.4 on 2021-06-12 00:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('phone', models.CharField(max_length=200, verbose_name='Telefone')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HelpDesk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client', verbose_name='Cliente')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Mensagem')),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='Arquivo')),
                ('type', models.CharField(choices=[('received', 'Recebida'), ('sent', 'Enviada')], default='sent', max_length=50, verbose_name='Tipo da mensagem')),
                ('help_desk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.helpdesk', verbose_name='Atendimento')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
