# Generated by Django 3.2.4 on 2021-06-12 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('sending', 'Enviando'), ('sent', 'Enviado')], default='sending', max_length=50, verbose_name='Status'),
        ),
    ]
