# Generated by Django 3.2.4 on 2021-06-14 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_message_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpdesk',
            name='organization',
            field=models.CharField(default='org1', max_length=255, verbose_name='Organização'),
        ),
    ]
